[project]
name = "babybook-admin"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "typer>=0.12.3",
  "rich>=13.7.1",
  "asyncpg>=0.29.0",
  "sqlalchemy[asyncio]>=2.0.31",
  "alembic>=1.13.2"
]

[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"
